baseURL = "https://enet.ada-risques.fr/"
languageCode = "fr-FR"
title = "e-net"
author = "AdA Risques"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "ada-kanzan"

[server]
    [[server.headers]]
        for = "/**.vue"
        [server.headers.values]
            Content-Type = "application/javascript"